name: file_name

on:
  workflow_dispatch:
    inputs:
      input1:
        description: name_file
        type: string
        required: true
      input2:
        description: vrednost
        type: string
        required: true
jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echoing
        run: |
          echo " ${{ github.event.inputs.input1 }}"
          echo " ${{ github.event.inputs.input2 }}"
      - name: pretraga
        run: |
          source ./naziv_fajla.sh ${{ github.event.inputs.input1 }} ${{ github.event.inputs.input2 }}
   