name: file_name

on:
  workflow_dispatch:
    inputs:
      file:
        description: name file
        type: string
        required: true
      vrednost:
        description: vrednost
        type: string
        required: true
jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echoing
        run: |
          echo " ${{ github.event.inputs.naziv_fajla }}"
          echo " ${{ github.event.inputs.vrednost }}"
      - name: pretraga
        run: |
          source ./naziv_fajla.sh ${{ github.event.inputs.naziv_fajla }}" ${{ github.event.inputs.vrednost }}"
    