name: zadatak sa inputima

on:
  workflow_dispatch:
    inputs:
      inputs1:
        description: Unijeti prvi input
        type: string
        required: true
      inputs2:
        description: Unijeti drugi input
        type: string
        required: true
      
jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing
        run: |
          echo " ${{ github.event.inputs.inputs1 }}"
          echo " ${{ github.event.inputs.inputs2 }}"
      - name: Sum
        run: |
          source ./input.sh ${{ github.event.inputs.inputs1 }} ${{ github.event.inputs.inputs2 }}
          