name: name_file

on:
  workflow_dispatch:
    inputs:
      inputs1:
        description: name file
        type: string
        required: true
jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Doc
        run: mvn dokka:dokka -f pom.txt
      - name: Echoing
        run: |
          echo " ${{ github.event.inputs.inputs1 }}"