name: inkrementacija
on:
  push:
    paths-ignore:
      - 'zakazani_brojac/**'
    branches:
      - main
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: increment1
        run: |
          cat brojac/increment1.txt
          source ./increment.bash 2
          source ./increment.bash $(cat brojac/increment1.txt
          echo $(source ./increment.bash $(cat brojac/increment1.txt)) > brojac/increment1.txt
      - name: push_changes
        run: | 
          git config --local user.email "example@example.com"
          git config --local user.name "AntVil"
          git add .
          git commit -m "123" 
          git push

