name: inkrementacija
on:
  push:
    branches:
      - main
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: increment1
        run: |
          cd brojac
          echo "1" >> increment1.txt
      - name: push_changes
        run: | 
          git config --local user.email "example@example.com"
          git config --local user.name "AntVil"
          git add .
          git commit -m "123" 
          git push

