name: inkrementacija1
on:
  push:
    paths-ignore:
      - 'zakazani_brojac/**'
    branches:
      - main
jobs: 
  job1:
    runs-on: ubuntu-latest
    outputs:
      vrijednost1: ${{ steps.increment1.outputs.vrijednost }}
      vrijednost2: ${{ steps.increment2.outputs.vrijednost2 }}
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: increment1
        id: increment1
        run: |
          echo $(source ./increment.sh $(cat brojac/increment1.txt)) > brojac/increment1.txt
          export INCREMENT_VALUE=$(cat brojac/increment1.txt)
          echo "vrijednost=$INCREMENT_VALUE" >> $GITHUB_OUTPUT
      - name: increment2
        id: increment2
        run: |
          echo $(source ./increment2.sh $(cat brojac/increment2.txt)) > brojac/increment2.txt
          export INCREMENT_VALUE2=$(cat brojac/increment2.txt)
          echo "vrijednost2=$INCREMENT_VALUE2" >> $GITHUB_OUTPUT
      - name: push_changes
        run: | 
          git config --local user.email "example@example.com"
          git config --local user.name "AntVil"
          git add .
          git commit -m "123" 
          git push
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: outputs
        run : |
          echo ${{needs.job1.outputs.vrijednost1}}
          echo ${{needs.job2.outputs.vrijednost2}}


